# Generated by Django 3.1.5 on 2021-03-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_auto_20210311_1519'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
