# Generated by Django 3.1.5 on 2021-03-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_auto_20210311_1528'),
        ('users', '0003_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
