# Generated by Django 3.1.5 on 2021-03-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('instructor', models.CharField(max_length=150)),
                ('link', models.URLField(max_length=2000)),
                ('tags', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=150)),
                ('last_updated', models.DateField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('estimated_learning_hours', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
    ]
