# Generated by Django 3.1.5 on 2021-03-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoriallist',
            name='difficulty',
            field=models.CharField(choices=[('Begginer', 'Begginer'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tutoriallist',
            name='language',
            field=models.CharField(choices=[('Korean', 'Korean'), ('English', 'English')], max_length=100),
        ),
    ]
