# Generated by Django 3.1.5 on 2021-03-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20210309_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tutoriallist',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='tutoriallist',
            name='tags',
        ),
        migrations.AddField(
            model_name='tutoriallist',
            name='tags',
            field=models.ManyToManyField(to='hub.Tag'),
        ),
    ]
