# Generated by Django 3.1.5 on 2021-03-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_curriculum_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='tags',
            field=models.ManyToManyField(to='hub.Tag'),
        ),
    ]
