# Generated by Django 3.1.5 on 2021-03-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_curriculum_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='tags',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='tutorial_topic',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
