# Generated by Django 3.1.5 on 2021-03-11 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('hub', '0006_auto_20210309_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='tutorial_topic',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='tutoriallist',
            old_name='estimated_learning_hours',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='student',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='tutorial',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='goal',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='note',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='CurriculumItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.curriculum')),
                ('tutorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.tutoriallist')),
            ],
        ),
    ]
