# Generated by Django 3.1.5 on 2021-03-11 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer'),
        ('hub', '0008_auto_20210311_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
